apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "radar-upload-connect-backend.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "radar-upload-connect-backend.name" . }}
    helm.sh/chart: {{ include "radar-upload-connect-backend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "radar-upload-connect-backend.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "radar-upload-connect-backend.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: "app.kubernetes.io/name"
                    operator: In
                    values:
                    - {{ template "radar-upload-connect-backend.name" . }}
                  - key: "app.kubernetes.io/instance"
                    operator: In
                    values:
                    - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - radar-upload-backend
            - /etc/upload-backend/upload.yml
          env:
          - name: JAVA_OPTS
            value: "-Dlogback.configurationFile=/etc/upload-backend/logback.xml"
          ports:
            - name: http
              containerPort: 8085
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8085
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8085
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/upload-backend/
            - name: private-keys
            # - name: output
            #   mountPath: /output
      volumes:
        - name: config
          configMap:
            name: {{ include "radar-upload-connect-backend.fullname" . }}
        # - name: output
        # {{- if .Values.persistence.enabled }}
        #   persistentVolumeClaim:
        #     claimName: {{ .Values.persistence.existingClaim | default (include "radar-upload-connect-backend.fullname" .) }}
        # {{- else }}
        #   emptyDir: {}
        # {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
