apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "radar-gateway.fullname" . }}
  labels:
    app: {{ template "radar-gateway.name" . }}
    chart: {{ template "radar-gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  gateway.yml: |
    # Resource config class
    #resourceConfig: org.radarbase.gateway.inject.ManagementPortalEnhancerFactory

    server:
      baseUri: http://0.0.0.0/radar-gateway/

    kafka:
      producer:
        bootstrap.servers: {{ .Values.bootstrapServers }}
      serialization:
        schema.registry.url: {{ .Values.schemaRegistry }}

    auth:
      managementPortalUrl: http://{{ .Values.managementportalHost }}:8080/managementportal
