apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "radar-gateway.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "radar-gateway.name" . }}
    helm.sh/chart: {{ include "radar-gateway.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "radar-gateway.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret-is: {{ include (print $.Template.BasePath "/secret-is.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "radar-gateway.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: "app.kubernetes.io/name"
                    operator: In
                    values:
                    - {{ template "radar-gateway.name" . }}
                  - key: "app.kubernetes.io/instance"
                    operator: In
                    values:
                    - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["radar-gateway", "/etc/radar-gateway/gateway.yml"]
          env:
          - name: RADAR_IS_CONFIG_LOCATION
            value: "/etc/radar-gateway/is/radar-is.yml"
          - name: JAVA_OPTS
            value: "-XX:GCTimeRatio=19 -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=30"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - curl -IX localhost/radar-gateway/topics 2>&1 | grep -q 401 || exit 1
            initialDelaySeconds: 5
            periodSeconds: 90
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - curl -IX localhost/radar-gateway/topics 2>&1 | grep -q 401 || exit 1
            initialDelaySeconds: 5
            periodSeconds: 90
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/radar-gateway
            - name: is
              mountPath: /etc/radar-gateway/is
      volumes:
        - name: config
          configMap:
            name: {{ include "radar-gateway.fullname" . }}
        - name: is
          secret:
            secretName: {{ include "radar-gateway.fullname" . }}-is
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
