apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "radar-gateway.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "radar-gateway.name" . }}
    helm.sh/chart: {{ include "radar-gateway.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "radar-gateway.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "radar-gateway.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["radar-gateway", "/etc/radar-gateway/gateway.yml"]
          env:
          - name: RADAR_IS_CONFIG_LOCATION
            value: "/etc/radar-gateway/radar-is.yml"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - wget --spider localhost/radar-gateway/topics 2>&1 | grep -q 401 || exit 1
            initialDelaySeconds: 5
            periodSeconds: 90
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - wget --spider localhost/radar-gateway/topics 2>&1 | grep -q 401 || exit 1
            initialDelaySeconds: 5
            periodSeconds: 90
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/radar-gateway
      volumes:
        - name: config
          configMap:
            name: {{ include "radar-gateway.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
