apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "radar-gateway.fullname" . }}-jmx-configmap
data:
  config.yml: |
    jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:9010/jmxrmi
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    ssl: false
