# KSQL configuration options
## ref: https://docs.confluent.io/current/ksql/docs/installation/server-config/config-reference.html
kafka:
    bootstrapServers: PLAINTEXT://cp-kafka:9092
cp-schema-registry:
    url: http://cp-schema-registry:8081
ksql:
    headless: false
configurationOverrides:
    "ksql.server.url": "http://0.0.0.0:8088"
    "ksql.advertised.listener": "http://ksql-server:8088"
    "ksql.logging.processing.topic.auto.create": true
    "ksql.logging.processing.stream.auto.create": true
    "ksql.service.id": radar_default_
    "ksql.persistence.default.format.key": AVRO
    "ksql.persistence.default.format.value": AVRO
    "ksql.sink.replicas": 3
    "ksql.streams.replication.factor": 3
    "ksql.internal.topic.replicas": 3
    "log4j.logger.processing": false
