apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "radar-s3-connector.fullname" . }}
  labels:
    app: {{ template "radar-s3-connector.name" . }}
    chart: {{ template "radar-s3-connector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  sink-s3.properties: |
    name=radar-s3-sink-connector
    connector.class=io.confluent.connect.s3.S3SinkConnector
    tasks.max={{ .Values.maxTasks | int }}
    topics={{ .Values.topics }}
    flush.size={{ .Values.flushSize | int }}
    s3.bucket.name={{ .Values.bucketName }}
    {{- if .Values.s3Region }}
    s3.region={{ .Values.s3Region }}
    {{- end }}
    s3.part.size={{ .Values.s3PartSize | int }}
    s3.object.tagging={{ .Values.s3Tagging }}
    connect.meta.data=false
    {{- if not .Values.s3Region }}
    store.url={{ .Values.s3Endpoint }}
    {{- end }}
    storage.class=io.confluent.connect.s3.storage.S3Storage
    format.class=io.confluent.connect.s3.format.avro.AvroFormat
    transforms=combineKeyValue
    transforms.combineKeyValue.type=org.radarbase.kafka.connect.transforms.CombineKeyValue
    rotate.schedule.interval.ms={{ .Values.rotateInterval | int }}
    timezone=UTC
    avro.codec=deflate
    errors.tolerance=all
    errors.log.enable=true
    errors.deadletterqueue.topic.name=dead_letter_queue_s3
    errors.deadletterqueue.topic.replication.factor=3
    errors.deadletterqueue.context.headers.enable=true
    errors.retry.delay.max.ms=60000
    errors.retry.timeout=300000
  healthcheck.sh: |
    #!/bin/sh
    STATUS=$(curl -sf localhost:8083/connectors/radar-s3-sink-connector/status | grep -o '\"state\":\"[^\"]*\"')
    if echo "$STATUS" | tr '\\n' ',' | grep -q FAILED; then
      exit 1
    elif [ $(echo "$STATUS" | grep RUNNING | wc -l) -le 1 ]; then
      exit 1
    fi
