apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "radar-s3-connector.fullname" . }}-init
  labels:
    app: {{ template "radar-s3-connector.name" . }}
    chart: {{ template "radar-s3-connector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  add-topics-to-config.sh: |
    #!/bin/sh
    SOURCE=$1
    TARGET=$2
    set -e
    apk add --no-cache curl jq
    TOPICS=$(curl -f {{ .Values.catalogServer.url }}/source-types | jq -r '[to_entries[] | select(.key|endswith("source-types")) | .value[].data[].topic] | unique | join(",")')
    sed "s/^topics=.\+\$/\\0,$TOPICS/" "$SOURCE" | sed "s/^topics=\$/\\0$TOPICS/" > "$TARGET"
