{{- if .Values.cc.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "catalog-server.fullname" . }}-java-config
  labels:
    app: {{ template "catalog-server.name" . }}
    chart: {{ template "catalog-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  java-config.properties: |
    # Kafka
    bootstrap.servers={{ .Values.cc.bootstrapServerurl }}
    security.protocol=SASL_SSL
    sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="{{ .Values.cc.apiKey }}" password="{{ .Values.cc.apiSecret }}";
    ssl.endpoint.identification.algorithm=https
    sasl.mechanism=PLAIN

    # Confluent Cloud Schema Registry
    schema.registry.url={{ .Values.schema_registry}}
    basic.auth.credentials.source=USER_INFO
    schema.registry.basic.auth.user.info={{ .Values.cc.schemaRegistryApiKey }}:{{ .Values.cc.schemaRegistryApiSecret }}
{{- end -}}