repositories:
  - name: jetstack
    url: https://charts.jetstack.io

# helmDefaults:
#   atomic: true

releases:
  - name: cert
    namespace: cert-manager
    chart: ./charts/cert
    values:
      - server_name: {{ requiredEnv "SERVER_NAME" }}
        maintainer_email: {{ requiredEnv "MAINTAINER_EMAIL" }}

  - name: prometheus-operator
    chart: stable/prometheus-operator
    namespace: monitoring
    values:
      - "charts/prometheus-operator/values.yaml"
      - prometheus:
          ingress:
            hosts: ["prometheus.{{ requiredEnv "SERVER_NAME" }}"]
            tls:
            - secretName: radar-base-tls
              hosts: ["prometheus.{{ requiredEnv "SERVER_NAME" }}"]
        alertmanager:
          ingress:
            hosts: ["alertmanager.{{ requiredEnv "SERVER_NAME" }}"]
            tls:
            - secretName: radar-base-tls
              hosts: ["alertmanager.{{ requiredEnv "SERVER_NAME" }}"]
        grafana:
          ingress:
            hosts: ["grafana.{{ requiredEnv "SERVER_NAME" }}"]
            tls:
            - secretName: radar-base-tls
              hosts: ["grafana.{{ requiredEnv "SERVER_NAME" }}"]

  - name: nginx-ingress
    chart: stable/nginx-ingress
    values:
      - "charts/nginx-ingress/values.yaml"

  - name: cp-kafka
    chart: ./cp-helm-charts/charts/cp-kafka
    values:
      - "charts/cp-kafka/values.yaml"
      - cp-zookeeper:
          url: "cp-zookeeper-headless:2181"
        brokers: "3"
  - name: cp-kafka-rest
    chart: ./cp-helm-charts/charts/cp-kafka-rest
    values:
      - "charts/cp-kafka-rest/values.yaml"
      - cp-schema-registry:
          url: "http://cp-schema-registry:8081"
        cp-zookeeper:
          url: "cp-zookeeper-headless:2181"
  - name: cp-schema-registry
    chart: ./cp-helm-charts/charts/cp-schema-registry
    values:
      - "charts/cp-schema-registry/values.yaml"
      - kafka:
          bootstrapServers: "PLAINTEXT://cp-kafka-headless:9092"
        ingress:
          hosts:
            - host: {{ requiredEnv "SERVER_NAME" }}
              paths: ["/schema/"]
          tls:
          - secretName: radar-base-tls
            hosts:
            - {{ requiredEnv "SERVER_NAME" }}
  - name: cp-zookeeper
    chart: ./cp-helm-charts/charts/cp-zookeeper
    values:
      - "charts/cp-zookeeper/values.yaml"
  - name: kafka-manager
    chart: stable/kafka-manager
    values:
      - "charts/kafka-manager/values.yaml"
      - ingress:
          hosts:
            - {{ requiredEnv "SERVER_NAME" }}
          tls:
          - secretName: radar-base-tls
            hosts: ["{{ requiredEnv "SERVER_NAME" }}"]
        zkHosts: cp-zookeeper:2181
  - name: postgresql
    chart: stable/postgresql
    values:
      - "charts/postgresql/values.yaml"
      - replication:
          password: repl_password
        postgresqlPassword: password

  - name: catalog-server
    chart: ./charts/catalog-server
    values:
    - image:
        tag: 0.4.3
      replicaCount: 1
      kafka_num_brokers: 3
      zookeeper: cp-zookeeper-headless:2181
      schema_registry: http://cp-schema-registry:8081
