helmDefaults:
  atomic: true

releases:
  - name: radar-fitbit-connector
    chart: ./charts/radar-fitbit-connector
    values:
    - image:
        tag: "{{ requiredEnv "RADAR_FITBIT_CONNECTOR_IMAGE_TAG" }}"
      replicaCount: "{{ requiredEnv "RADAR_FITBIT_CONNECTOR_REPLICA_COUNT" }}"
      kafka_num_brokers: "{{ requiredEnv "KAFKA_NUM_BROKERS" }}"
      fitbit_api_client: "{{ requiredEnv "FITBIT_API_CLIENT_ID" }}"
      fitbit_api_secret: "{{ requiredEnv "FITBIT_API_CLIENT_SECRET" }}"
  - name: radar-integration
    chart: ./charts/radar-integration
    values:
    - image:
        tag: "{{ requiredEnv "RADAR_INTEGRATION_IMAGE_TAG" }}"
      replicaCount: "{{ requiredEnv "RADAR_INTEGRATION_REPLICA_COUNT" }}"
  - name: radar-rest-sources-authorizer
    chart: ./charts/radar-rest-sources-authorizer
    values:
    - image:
        tag: "{{ requiredEnv "RADAR_REST_SOURCES_AUTHORIZER_IMAGE_TAG" }}"
      replicaCount: "{{ requiredEnv "RADAR_REST_SOURCES_AUTHORIZER_REPLICA_COUNT" }}"
      fitbit_api_client: "{{ requiredEnv "FITBIT_API_CLIENT_ID" }}"
      fitbit_api_secret: "{{ requiredEnv "FITBIT_API_CLIENT_SECRET" }}"
  - name: radar-rest-sources-backend
    chart: ./charts/radar-rest-sources-backend
    values:
    - image:
        tag: "{{ requiredEnv "RADAR_REST_SOURCES_BACKEND_IMAGE_TAG" }}"
      replicaCount: "{{ requiredEnv "RADAR_REST_SOURCES_BACKEND_REPLICA_COUNT" }}"
      postgres:
        password: "{{ requiredEnv "POSTGRES_PASSWORD" }}"
