helmDefaults:
  atomic: true

releases:
  - name: hdfs-datanode
    chart: ./charts/hdfs
    values:
    - "charts/hdfs/values-datanode.yaml"
    - image:
        tag: 3.0.3-alpine
      replicaCount: 3
  - name: hdfs-namenode
    chart: ./charts/hdfs
    values:
    - "charts/hdfs/values-namenode.yaml"
    - image:
        tag: 3.0.3-alpine
      replicaCount: 1
  - name: management-portal
    chart: ./charts/management-portal
    values:
    - image:
        tag: 0.5.3
      ingress:
        hosts:
          - host: localhost
            paths:
              - /managementportal
      replicaCount: 1
      server_name: localhost
      catalogue_server: catalog-server
      postgres:
        host: postgresql-postgresql
        password: password
  - name: radar-backend-monitor
    chart: ./charts/radar-backend
    values:
    - "charts/radar-backend/values-monitor.yaml"
    - image:
        tag: 0.4.0
      replicaCount: 1
      zookeeper: cp-zookeeper-headless:2181
      kafka: cp-kafka-headless:9092
      rest_proxy: http://cp-kafka-rest:8082
      schema_registry: http://cp-schema-registry:8081
      kafka_num_brokers: "3"
  - name: radar-backend-stream
    chart: ./charts/radar-backend
    values:
    - "charts/radar-backend/values-stream.yaml"
    - image:
        tag: 0.4.0
      replicaCount: 1
      zookeeper: cp-zookeeper-headless:2181
      kafka: cp-kafka-headless:9092
      rest_proxy: http://cp-kafka-rest:8082
      schema_registry: http://cp-schema-registry:8081
      kafka_num_brokers: "3"
  - name: radar-connect-hdfs-sink
    chart: ./charts/radar-connect-hdfs-sink
    values:
    - image:
        tag: 0.2.0
      replicaCount: 1
      zookeeper: cp-zookeeper-headless:2181
      kafka: PLAINTEXT://cp-kafka-headless:9092
      kafka_num_brokers: "3"
      schema_registry: http://cp-schema-registry:8081
      hdfs_url: hdfs-namenode
  - name: radar-dashboard
    chart: ./charts/radar-dashboard
    values:
    - image:
        tag: 2.1.0
      ingress:
        hosts:
          - host: localhost
            paths:
              - /dashboard/?(.*)
      replicaCount: 1
      server_name: localhost
  - name: radar-gateway
    chart: ./charts/radar-gateway
    values:
    - image:
        tag: 0.3.7
      ingress:
        hosts:
          - host: localhost
            paths:
              - /kafka/?(.*)
      replicaCount: 1
      managementportal_host: management-portal
      rest_proxy: http://cp-kafka-rest:8082
      schema_registry: http://cp-schema-registry:8081
  - name: radar-hotstorage
    chart: ./charts/radar-hotstorage
    values:
    - image:
        tag: 0.1
      replicaCount: 1
      hotstorage:
        username: mongodb-user
        password: password
        name: mongodb-database
  - name: radar-mongodb-connector
    chart: ./charts/radar-mongodb-connector
    values:
    - image:
        tag: 0.2.2
      replicaCount: 1
      zookeeper: cp-zookeeper-headless:2181
      kafka: PLAINTEXT://cp-kafka-headless:9092
      kafka_num_brokers: "3"
      schema_registry: http://cp-schema-registry:8081
      mongodb:
        host: radar-hotstorage
        username: mongodb-user
        password: password
        database_name: mongodb-database
  - name: radar-restapi
    chart: ./charts/radar-restapi
    values:
    - image:
        tag: 0.3
      replicaCount: 1
      managementportal_host: management-portal
      mongodb:
        host: radar-hotstorage
        username: mongodb-user
        password: password
        database_name: mongodb-database
