apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: {{ include "ceph.fullname" . }}
  labels:
{{ include "ceph.labels" . | indent 4 }}
spec:
  metadataPool:
    replicated:
      size: 3
  dataPools:
    - replicated:
        size: 3
  preservePoolsOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: true
