apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "radar-connect-hdfs-sink.fullname" . }}
  labels:
    app: {{ template "radar-connect-hdfs-sink.name" . }}
    chart: {{ template "radar-connect-hdfs-sink.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  sink-hdfs.properties: |
    name=radar-hdfs-sink-android-15000
    connector.class=io.confluent.connect.hdfs.HdfsSinkConnector
    tasks.max=4
    topics={{ .Values.topics }}
    flush.size=80000
    rotate.interval.ms=900000
    hdfs.url=hdfs://{{ .Values.hdfs_url }}:8020
    format.class=org.radarcns.sink.hdfs.AvroFormatRadar
    topics.dir=topicAndroidNew
    avro.codec=snappy
