apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "radar-output.fullname" . }}-keys
  labels:
    app: {{ template "radar-output.name" . }}
    chart: {{ template "radar-output.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  id_rsa.pub: |
    {{ .Values.sftp_user_keys }}
