apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "management-portal.fullname" . }}
  labels:
    app: {{ template "management-portal.name" . }}
    chart: {{ template "management-portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  healthcheck.sh: |
    #!/bin/sh
    STATUS=$(wget -T 1 -O - localhost:8080/managementportal/management/health)
    if ! (echo "$STATUS" | grep -Fq 'db":{"status":"UP'); then
      exit 1
    fi
