{{- if (include "management-portal.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "management-portal.fullname" . }}
  labels:
    app: {{ template "management-portal.name" . }}
    chart: {{ template "management-portal.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  postgresql_password: {{ include "management-portal.postgres.password" . | b64enc | quote }}
  managementportal_frontend_client_secret: {{ include "management-portal.managementportal.frontend_client_secret" . | b64enc | quote }}
  managementportal_common_admin_password: {{ include "management-portal.managementportal.common_admin_password" . | b64enc | quote }}
{{- end -}}
