apiVersion: v1
kind: Secret
metadata:
  name: {{ template "management-portal.fullname" . }}-keystore
  labels:
    app: {{ template "management-portal.name" . }}
    chart: {{ template "management-portal.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  keystore.p12: {{ .Values.keystore | quote }}
