apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "radar-hotstorage.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "radar-hotstorage.name" . }}
    helm.sh/chart: {{ include "radar-hotstorage.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "radar-hotstorage.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "radar-hotstorage.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: RADAR_USER
            value: "{{ .Values.hotstorage.username }}"
          - name: RADAR_PWD
            valueFrom:
              secretKeyRef:
                name: {{ template "radar-hotstorage.secretName" . }}
                key: hotstorage_password
          - name: RADAR_DB
            value: "{{ .Values.hotstorage.name }}"
          ports:
            - name: http
              containerPort: 27017
              protocol: TCP
            - name: stats
              containerPort: 28017
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - mongo -u $RADAR_USER -p $RADAR_PWD $RADAR_DB --eval db
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - mongo -u $RADAR_USER -p $RADAR_PWD $RADAR_DB --eval db
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: db
              mountPath: /data/
      volumes:
        - name: db
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "radar-hotstorage.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
