{{- if (include "radar-hotstorage.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "radar-hotstorage.fullname" . }}
  labels:
    app: {{ template "radar-hotstorage.name" . }}
    chart: {{ template "radar-hotstorage.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  hotstorage_password: {{ .Values.hotstorage.password | b64enc | quote }}
{{- end -}}
