apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "smtp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "smtp.name" . }}
    helm.sh/chart: {{ include "smtp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "smtp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "smtp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        backup.velero.io/backup-volumes: exim
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: "app.kubernetes.io/name"
                    operator: In
                    values:
                    - {{ template "smtp.name" . }}
                  - key: "app.kubernetes.io/instance"
                    operator: In
                    values:
                    - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: SMARTHOST_ADDRESS
            value: "{{ .Values.smarthost.address }}"
          - name: SMARTHOST_PORT
            value: "{{ .Values.smarthost.port }}"
          - name: SMARTHOST_USER
            value: "{{ .Values.smarthost.user }}"
          - name: SMARTHOST_PASSWORD
            value: "{{ .Values.smarthost.password }}"
          - name: SMARTHOST_ALIASES
            value: "{{ .Values.smarthost.aliases }}"
          - name: RELAY_NETWORKS
            value: "{{ .Values.relay_networks }}"
          ports:
            - name: smtp
              containerPort: 25
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: smtp
          readinessProbe:
            tcpSocket:
              port: smtp
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: exim
              mountPath: /var/spool/exim
      volumes:
        - name: exim
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "smtp.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
