receivers: |
  slack_config:
    api_url: "https://hooks.slack.com/services/XXXXXX/XXXXXX/XXXXXXXXXX"
    channel: "#alerts"

nginx_auth: |
  test:$2y$05$/okvi.SPEUOHzFuW/lao0ejB.2XBQMDw2pNVxag8R.nKVr5Y/7pGm
  
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: "false"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      certmanager.k8s.io/acme-challenge-type: http01
      certmanager.k8s.io/issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: nginx-auth
    hosts:
      - localhost
    tls:
    - secretName: radar-base-tls
      hosts:
      - localhost

alertmanager:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      certmanager.k8s.io/acme-challenge-type: http01
      certmanager.k8s.io/issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: nginx-auth
    hosts:
      - localhost
    tls:
    - secretName: radar-base-tls
      hosts:
      - localhost

grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      certmanager.k8s.io/acme-challenge-type: http01
      certmanager.k8s.io/issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: nginx-auth
    hosts:
      - localhost
    tls:
    - secretName: radar-base-tls
      hosts:
      - localhost
