apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "radar-rest-sources-authorizer.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "radar-rest-sources-authorizer.name" . }}
    helm.sh/chart: {{ include "radar-rest-sources-authorizer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "radar-rest-sources-authorizer.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "radar-rest-sources-authorizer.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: "app.kubernetes.io/name"
                    operator: In
                    values:
                    - {{ template "radar-rest-sources-authorizer.name" . }}
                  - key: "app.kubernetes.io/instance"
                    operator: In
                    values:
                    - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: BASE_HREF
            value: /rest-sources/authorizer/
          - name: BACKEND_BASE_URL
            value: {{ .Values.restSourceBackendUrl }}
          - name: VALIDATE
            value: "true"
          - name: AUTH_GRANT_TYPE
            value: "authorization_code"
          - name: AUTH_CLIENT_ID
            value: {{ .Values.clientId }}
          - name: AUTH_CLIENT_SECRET
            value: ""
          - name: AUTH_CALLBACK_URL
            value: {{ .Values.callbackUrl }}
          - name: AUTH_URI
            value: {{ .Values.managementPortalUrl }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - wget --spider http://localhost:80
            initialDelaySeconds: 5
            periodSeconds: 90
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - wget --spider http://localhost:80
            initialDelaySeconds: 5
            periodSeconds: 90
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
