apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app-config.fullname" . }}
  labels:
    app: {{ template "app-config.name" . }}
    chart: {{ template "app-config.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  healthcheck.sh: |
    #!/bin/sh
    STATUS=$(curl -s --max-time 4 localhost:8090/appconfig/api/health)
    if ! (echo "$STATUS" | grep -Fq 'db":{"status":"UP'); then
      exit 1
    fi
  appconfig.yml: |
    baseUri: http://0.0.0.0:8090/appconfig/api
    isJmxEnabled: false

    inject:
      enhancerFactory: org.radarbase.appconfig.inject.ManagementPortalEnhancerFactory

    auth:
      managementPortal:
        url: http://management-portal:8080/managementportal
      jwtResourceName: res_appconfig

    database:
      driver: {{ .Values.jdbc.driver }}
      dialect: {{ .Values.jdbc.dialect }}

    hazelcast:
      network:
        port: 5801
        join:
          multicastConfig:
            enabled: false
          kubernetesConfig:
            enabled: true
            properties:
              service-name: {{ template "app-config.fullname" . }}
              service-port: 5801
              namespace: {{ .Values.namespace }}
