apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app-config.fullname" . }}
  labels:
    app: {{ template "app-config.name" . }}
    chart: {{ template "app-config.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  appconfig.yml: |
    baseUri: http://0.0.0.0:8090/appconfig/api
    isJmxEnabled: false

    inject:
      enhancerFactory: org.radarbase.appconfig.inject.ManagementPortalEnhancerFactory

    auth:
      managementPortal:
        url: http://management-portal:8080/managementportal
      jwtResourceName: res_appconfig

    database:
      driver: {{ .Values.jdbc.driver }}
      dialect: {{ .Values.jdbc.dialect }}
