apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app-config.fullname" . }}
  labels:
    app: {{ template "app-config.name" . }}
    chart: {{ template "app-config.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  appconfig.yml: |
    baseUri: http://0.0.0.0:8090/appconfig/api
    isJmxEnabled: false

    inject:
      enhancerFactory: org.radarbase.appconfig.inject.ManagementPortalEnhancerFactory

    auth:
      managementPortal:
        url: http://management-portal:8080/managementportal
        clientId: {{ .Values.clientId }}
        clientSecret: {{ .Values.clientSecret }}
      jwtResourceName: res_appconfig

    database:
      driver: {{ .Values.jdbc.driver }}
      url: "{{ .Values.jdbc.url }}"
      user: {{ .Values.jdbc.user }}
      password: {{ .Values.jdbc.password }}
      dialect: {{ .Values.jdbc.dialect }}
