{{- if (include "app-config.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app-config.fullname" . }}
  labels:
    app: {{ template "app-config.name" . }}
    chart: {{ template "app-config.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  managementPortalClientId: {{ .Values.clientId | b64enc | quote }}
  managementPortalClientSecret: {{ .Values.clientSecret | b64enc | quote }}
  databaseUrl: {{ .Values.jdbc.url | b64enc | quote }}
  databaseUser: {{ .Values.jdbc.user | b64enc | quote }}
  databasePassword: {{ .Values.jdbc.password | b64enc | quote }}
{{- end -}}
