apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-config.fullname" . }}-hazelcast
  labels:
{{ include "app-config.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: hazelcast
    targetPort: hazelcast
    protocol: TCP
    port: 5801
  selector:
    app.kubernetes.io/name: {{ include "app-config.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
