# Default values for radar-rest-sources-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: radarbase/radar-rest-source-auth-backend
  tag: 3.2.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: persistent
    nginx.ingress.kubernetes.io/session-cookie-path: /rest-sources/
    nginx.ingress.kubernetes.io/session-cookie-samesite: Strict
    nginx.ingress.kubernetes.io/session-cookie-max-age: "900"
    nginx.ingress.kubernetes.io/session-cookie-expires: "900"
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  path: "/rest-sources/backend/?(.*)"
  hosts:
    - localhost
  tls:
    secretName: radar-base-tls

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    cpu: 100m
    memory: 400Mi

nodeSelector: {}

tolerations: []

affinity: {}

postgres:
  host: postgresql
  port: 5432
  database: restsourceauthorizer
  connection_parameters: ""
  user: postgres
  password: password
  ssl:
    enabled: false
    keystorepassword: keystorepassword

managementportal_host: management-portal

client_secret: secret

restSourceClients:
  fitbit:
    enable: false
    sourceType: FitBit
    authorizationEndpoint: https://www.fitbit.com/oauth2/authorize
    tokenEndpoint: https://api.fitbit.com/oauth2/token
    clientId:
    clientSecret:
    scope: activity heartrate sleep profile
