kubeContext: default
server_name: example.com
maintainer_email: MAINTAINER_EMAIL@example.com
kafka_num_brokers: 3
postgres_password: password

# --------------------------------------------------------- 00-init.yaml ---------------------------------------------------------

graylog:
  _install: true

mongodb:
  _install: true
  architecture: replicaset
  auth:
    replicaSetKey: secret
    rootPassword: secret

elasticsearch:
  _install: true

cert_manager:
  _install: true

fluent_bit:
  _install: true

kube_prometheus_stack:
  _install: true
  kube-prometheus-stack:
    prometheus:
      prometheusSpec:
        replicas: 1
        storageSpec:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 10Gi
    alertmanager:
      #config:
      #  receivers:
      #    - name: default
      #      slack_configs:
      #        - api_url: https://hooks.slack.com/services/XXXXXX/XXXXXX/XXXXXXXXXX
      #          channel: "#radar-ops"
      alertmanagerSpec:
        replicas: 1
        storageSpec:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 1Gi

nginx_ingress:
  _install: true
  controller:
    replicaCount: 1
  metrics:
    enabled: "true"
    serviceMonitor:
      enabled: "true"

kafka_manager:
  _install: false
  basicAuth:
    enabled: true
    username: kafkamanager-user
    password: password

velero:
  _install: false
  objectStorageBackupReplicaCount: 1
  local:
    accessKey: accessKey
    secretKey: secretKey
  backup:
    address: s3.amazon.com  # protocol should not be specified
    bucket: radar-base-backups
    accessKey: accessKey
    secretKey: secretKey
  velero:
    configuration:
      backupStorageLocation:
        bucket: radar-base-backups
        config:
          s3Url: https://s3.amazon.com # protocol should be specified
    credentials:
      secretContents:
        cloud: |
          [default]
          aws_access_key_id=accessKey
          aws_secret_access_key=secretKey

# --------------------------------------------------------- 10-base.yaml ---------------------------------------------------------
confluent_cloud:
  enabled: false
  cc:
    bootstrapServerurl: confluentBootstrapServers
    schemaRegistryUrl: confluentSchemaRegistryUrl
    apiKey: ccApikey
    apiSecret: ccApiSecret
    schemaRegistryApiKey: srApiKey
    schemaRegistryApiSecret: srApiSecret

cp_zookeeper:
  _install: true
  servers: 3

cp_kafka:
  _install: true
  persistence:
    size: 10Gi

cp_schema_registry:
  _install: true
  replicaCount: 1

catalog_server:
  _install: true
  replicaCount: 1
  schema_registry: http://cp-schema-registry:8081

postgresql:
  _install: true
  replication:
    enabled: false
  persistence:
    size: 8Gi

management_portal:
  _install: true
  replicaCount: 1  # should be 1
  postgres:
    host: postgresql
    ssl:
      enabled: false
  managementportal:
    common_admin_password: password
    frontend_client_secret: password
    catalogue_server_enable_auto_import: true
    common_privacy_policy_url: http://info.thehyve.nl/radar-cns-privacy-policy
    oauth_checking_key_aliases_0: radarbase-managementportal-ec
    oauth_checking_key_aliases_1: selfsigned
  oauth_clients:
    pRMT:
      enable: true
      client_secret: "saturday$SHARE$scale"
    aRMT:
      enable: true
      client_secret: secret
    radar_upload_backend:
      client_secret: secret
    radar_upload_connect:
      client_secret: secret
    radar_rest_sources_auth_backend:
      client_secret: secret
    radar_redcap_integrator:
      client_secret: secret
    radar_fitbit_connector:
      client_secret: secret
    radar_appconfig:
      client_secret: secret
  smtp:
    enabled: false
    host: smtp
    port: 25
    from: noreply@example.com

app_config:
  _install: true
  replicaCount: 1
  jdbc:
    url: jdbc:postgresql://postgresql:5432/appconfig
    password: password

app_config_frontend:
  _install: true
  replicaCount: 1
  authUrl: https://example.com/managementportal/oauth
  callbackUrl: https://example.com/appconfig/login

# --------------------------------------------------------- 20-fitbit.yaml ---------------------------------------------------------
fitbit_api_client: fitbit_api_client_id
fitbit_api_secret: fitbit_api_client_secret

radar_fitbit_connector:
  _install: false
  replicaCount: 1
  oauthClientId: radar_fitbit_connector

radar_rest_sources_authorizer:
  _install: false
  replicaCount: 1

radar_rest_sources_backend:
  _install: false
  replicaCount: 1
  postgres:
    host: postgresql
    user: postgres
    password: password
    ssl:
      enabled: false
  # Clients example
  #restSourceClients:
  #  - sourceType: FitBit
  #    authorizationEndpoint: https://www.fitbit.com/oauth2/authorize
  #    tokenEndpoint: https://api.fitbit.com/oauth2/token
  #    clientId: clientId
  #    clientSecret: clientSecret
  #    scope: activity heartrate sleep profile

# --------------------------------------------------------- 20-ingestion.yaml ---------------------------------------------------------

radar_gateway:
  _install: true
  replicaCount: 1

# --------------------------------------------------------- 20-kafka-analysis.yaml ---------------------------------------------------------

radar_backend_monitor:
  _install: false
  replicaCount: 1
  persistence:
    size: 1Gi

radar_backend_stream:
  _install: false
  replicaCount: 1

# --------------------------------------------------------- 20-redcap.yaml ---------------------------------------------------------

radar_integration:
  _install: false
  replicaCount: 1
  oauth_client_id: radar_redcap_integrator
  projects: []
  # Example:
  #projects:
  #  - url: "http://example.com"
  #    project_id: "1"
  #    enrolment_event: enrolment
  #    integration_form: radar_integration
  #    token: xxx
  #    mp_info_project_name: RADAR-BASE

# --------------------------------------------------------- 20-upload.yaml ---------------------------------------------------------

radar_upload_postgres_password: password

radar_upload_postgresql:
  _install: true
  persistence:
    size: 8Gi

radar_upload_connect_backend:
  _install: true
  replicaCount: 1

radar_upload_connect_frontend:
  _install: true
  replicaCount: 1

radar_upload_source_connector:
  _install: true
  replicaCount: 1

# --------------------------------------------------------- 20-s3-connector.yaml ---------------------------------------------------------

redis:
  _install: true

# The access keys and secret keys of the following services should match.
# If S3 is used as a storage medium instead of minio, then fill in those.

minio:
  _install: true
  replicas: 4
  s3Endpoint: http://minio:9000/
  persistence:
    size: 20Gi
  accessKey: AKIAIOSFODNN7EXAMPLE
  secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

radar_s3_connector:
  # set to true if radar-s3-connector should be installed
  _install: true
  replicaCount: 1
  # The bucket name where intermediate data for cold storage should be written to.
  bucketName: radar-intermediate-storage
  s3Endpoint: http://minio:9000/
  topics: android_phone_usage_event_output,android_local_weather,android_phone_acceleration,android_phone_battery_level,android_phone_bluetooth_devices,android_phone_call,android_phone_contacts,android_phone_gyroscope,android_phone_light,android_phone_magnetic_field,android_phone_relative_location,android_phone_sms,android_phone_sms_unread,android_phone_step_count,android_phone_usage_event,android_phone_user_interaction,android_processed_audio,application_device_info,application_external_time,application_record_counts,application_server_status,application_time_zone,application_uptime,certh_banking_app_event,certh_banking_app_transaction,connect_fitbit_activity_log,connect_fitbit_intraday_calories,connect_fitbit_intraday_heart_rate,connect_fitbit_intraday_steps,connect_fitbit_sleep_classic,connect_fitbit_sleep_stages,connect_fitbit_time_zone,connect_upload_altoida_acceleration,connect_upload_altoida_action,connect_upload_altoida_attitude,connect_upload_altoida_bit_metrics,connect_upload_altoida_blink,connect_upload_altoida_diagnostics,connect_upload_altoida_domain_result,connect_upload_altoida_dot_metrics,connect_upload_altoida_eye_tracking,connect_upload_altoida_gravity,connect_upload_altoida_magnetic_field,connect_upload_altoida_metadata,connect_upload_altoida_object,connect_upload_altoida_path,connect_upload_altoida_rotation,connect_upload_altoida_summary,connect_upload_altoida_tap,connect_upload_altoida_touch,connect_upload_axivity_acceleration,connect_upload_axivity_battery_level,connect_upload_axivity_event,connect_upload_axivity_light,connect_upload_axivity_metadata,connect_upload_axivity_temperature,connect_upload_oxford_camera_data,connect_upload_oxford_camera_image,connect_upload_physilog_binary_data
  bucketAccessKey: AKIAIOSFODNN7EXAMPLE
  bucketSecretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

s3_proxy:
  _install: false
  replicaCount: 1
  target:
    provider: azureblob
  s3:
    identity: AKIAIOSFODNN7EXAMPLE
    credential: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

radar_output:
  _install: true
  replicaCount: 1
  source:
    s3:
      endpoint: http://minio:9000/
      bucket: radar-intermediate-storage
      accessToken: AKIAIOSFODNN7EXAMPLE
      secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  target:
    s3:
      endpoint: http://minio:9000/
      bucket: radar-output-storage
      accessToken: AKIAIOSFODNN7EXAMPLE
      secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

  redis:
    uri: redis://redis-master:6379

# --------------------------------------------------------- 30-confluent-cloud.yaml ---------------------------------------------------------

ccSchemaRegistryProxy:
  _install: false
  externalName: schema-registry-domain

# --------------------------------------------------------- 20-grafana.yaml ---------------------------------------------------------

timescaledb_db_name: grafana-metrics
timescaledb_password: password
timescaledb_username: postgres

grafana_password: password
grafana_metrics_username: username
grafana_metrics_password: password

radar_grafana:
  _install: true
  replicaCount: 1
  env:
    GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/allprojects/home.json

timescaledb:
  _install: true
  replicaCount: 1
  replication:
    enable: false
  persistence:
    size: 8Gi

radar_jdbc_connector:
  _install: true
  replicaCount: 1
