templates:
  logFailedRelease: &logFailedRelease
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "../bin/log-failed-release"
        args: ["{{ .Values.kubeContext }}", "{{ .Release.Namespace }}", "{{ .Release.Name }}", "{{ .Event.Error }}"]
