templates:
  logFailedRelease: &logFailedRelease
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "../bin/log-failed-release"
        args: ["-c", "'{{ .Values.kubeContext }}'", "-n", "'{{ .Release.Namespace }}'", "-r", "'{{ .Release.Name }}'", "-e", "'{{ .Event.Error }}'"]
