kafka:
  bootstrapServers: "PLAINTEXT://cp-kafka-headless:9092"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/acme-challenge-type: http01
    certmanager.k8s.io/issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    - host: localhost
      path: "/schema/?(.*)"
  tls:
  - secretName: radar-base-tls
    hosts:
    - localhost
