imageTag: 5.3.1

kafka:
  bootstrapServers: "PLAINTEXT://cp-kafka-headless:9092"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/configuration-snippet: |
      limit_except GET {
        deny all;
      }
  hosts:
    - host: localhost
      path: "/schema/?(.*)"
  tls:
  - secretName: radar-base-tls
    hosts:
    - localhost
