{{- define "prometheus.alertmanager_config" }}
global:
  resolve_timeout: 5m
receivers:
- name: "default"
{{ .Values.receivers }}
route:
  group_by:
  - job
  group_interval: 5m
  group_wait: 30s
  receiver: "default"
  repeat_interval: 12h
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "prometheus.fullname" . }}-alertmanager
  labels:
{{ include "prometheus.labels" . | indent 4 }}
data:
  alertmanager.yaml: {{ toYaml .Values.alertmanager_config | b64enc | quote }}
