apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kafka-manager.fullname" . }}
  labels:
{{ include "kafka-manager.labels" . | indent 4 }}
type: Opaque
data:
  {{ if .Values.applicationSecret }}
  applicationSecret:  {{ .Values.applicationSecret | b64enc | quote }}
  {{ else }}
  applicationSecret: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  basicAuthUsername:  {{ .Values.basicAuth.username | b64enc | quote }}
  {{ if .Values.basicAuth.password }}
  basicAuthPassword:  {{ .Values.basicAuth.password | b64enc | quote }}
  {{ else }}
  basicAuthPassword: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
