{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "kafka-manager.labels" . | indent 4 }}
  name: {{ template "kafka-manager.serviceAccountName" . }}
{{- end }}
