apiVersion: v1
kind: Service
metadata:
  name: {{ template "kafka-manager.fullname" . }}
  labels:
{{ include "kafka-manager.labels" . | indent 4 }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: kafka-manager
      port: {{ .Values.service.port }}
      targetPort: kafka-manager
      protocol: TCP
  selector:
    app: {{ template "kafka-manager.name" . }}
    release: {{ .Release.Name }}
