environments:
 default:
   values:
     - ../etc/base.yaml
     - ../etc/base-secrets.yaml
     - ../.github/ci_config/install-all.yaml
     - ../.github/ci_config/secrets.yaml.gotmpl

---

helmDefaults:
  atomic: {{ .Values.atomicInstall }}
  kubeContext: {{ .Values.kubeContext }}
  wait: true
  timeout: {{ .Values.timeout }}

repositories:
  - name: radar
    url: https://radar-base.github.io/radar-helm-charts
  - name: cp-radar
    url: https://radar-base.github.io/cp-helm-charts
