atomicInstall: false
base_timeout: 300

mongodb:
  _install: true

elasticsearch:
  _install: true
  resources:
    requests:
      cpu: "100m"
      memory: "500Mi"

graylog:
  _install: true

fluent_bit:
  _install: true

cert_manager:
  _install: true

kube_prometheus_stack:
  _install: true

nginx_ingress:
  _install: true

kafka_manager:
  _install: false

cert_manager_letsencrypt:
  _install: true

confluent_cloud:
  enabled: false

cp_zookeeper:
  _install: true

cp_kafka:
  _install: true
  persistence:
    size: 1Gi

cp_schema_registry:
  _install: true

catalog_server:
  _install: true

postgresql:
  _install: true
  primary:
    resources:
      requests:
        cpu: 50m
    persistence:
      size: 1Gi

management_portal:
  _install: true

app_config:
  _install: true

app_config_frontend:
  _install: true

radar_appserver_postgresql:
  _install: true
  primary:
    resources:
      requests:
        cpu: 50m  
    persistence:
      size: 1Gi

radar_appserver:
  _install: true

radar_fitbit_connector:
  _install: true

radar_rest_sources_authorizer:
  _install: true

radar_rest_sources_backend:
  _install: true

timescaledb:
  _install: true
  primary:
    resources:
      requests:
        cpu: 50m
    persistence:
      size: 1Gi

radar_grafana:
  _install: true

radar_jdbc_connector:
  _install: true

radar_gateway:
  _install: true

radar_backend_monitor:
  _install: true

radar_backend_stream:
  _install: true

radar_integration:
  _install: true

redis:
  _install: true

minio:
  _install: true
  persistence:
    size: 1Gi

radar_s3_connector:
  _install: true

s3_proxy:
  _install: true

radar_output:
  _install: true

radar_upload_postgresql:
  _install: true
  primary:
    resources:
      requests:
        cpu: 50m
    persistence:
      size: 1Gi

radar_upload_connect_backend:
  _install: true

radar_upload_connect_frontend:
  _install: true

radar_upload_source_connector:
  _install: true

ccSchemaRegistryProxy:
  _install: false

radar_push_endpoint:
  _install: true

radar_jdbc_connector_agg:
  _install: true

ksql_server:
  _install: true

velero:
  _install: true
