ingress:
  # -- Enable ingress controller resource
  enabled: true
  # -- Hosts to accept requests from
  hosts:
    - s3.example.com
  # -- Annotations that define default ingress class, certificate issuer
  # @default -- check values.yaml
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi

  # -- CPU/Memory resource requests
  requests:
    cpu: 100m
    memory: 400Mi

# -- Number of nodes, 4 is minimum for distributed mode
replicas: 4

# -- MinIO server mode
mode: distributed

persistence:
  # -- Size of persistent volume claim
  size: 20Gi

# -- Default access key (5 to 20 characters)
accessKey: AKIAIOSFODNN7EXAMPLE
# -- Default secret key (8 to 40 characters)
secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

metrics:
  # -- Set this to true to create ServiceMonitor for Prometheus operator
  serviceMonitor:
    enabled: true

buckets:

  - # -- Bucket used for intermediate storage of RADAR-Base data
    name: radar-intermediate-storage
    # -- Public access is disabled for this bucket
    policy: none
    # -- Don't purge the bucket if already exists
    purge: false


  - # -- Bucket used for output storage of RADAR-Base data
    name: radar-output-storage
    # -- Public access is disabled for this bucket
    policy: none
    # -- Don't purge the bucket if already exists
    purge: false
