## minio server mode, i.e. standalone or distributed.
## Distributed Minio ref: https://docs.minio.io/docs/distributed-minio-quickstart-guide
##
mode: distributed

## Set default accesskey, secretkey, Minio config file path, volume mount path and
## number of nodes (only used for Minio distributed mode)
## AccessKey and secretKey is generated when not set
## Distributed Minio ref: https://docs.minio.io/docs/distributed-minio-quickstart-guide
##
# -- Default access key (5 to 20 characters)
accessKey: AKIAIOSFODNN7EXAMPLE
# -- Default secret key (8 to 40 characters)
secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

# Number of MinIO containers running
# 4 is minimum for distributed mode
replicas: 4

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  # -- Size of persistent volume claim
  size: 20Gi

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - s3.example.com

apiIngress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - api.s3.example.com

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    cpu: 100m
    memory: 400Mi

## Create multiple buckets after minio install
## Enabling `defaultBucket` will take priority over this list
##
buckets:

  - # -- Bucket used for intermediate storage of RADAR-Base data
    name: radar-intermediate-storage
    # -- Public access is disabled for this bucket
    policy: none
    # -- Don't purge the bucket if already exists
    purge: false


  - # -- Bucket used for output storage of RADAR-Base data
    name: radar-output-storage
    # -- Public access is disabled for this bucket
    policy: none
    # -- Don't purge the bucket if already exists
    purge: false



metrics:
  # Metrics can not be disabled yet: https://github.com/minio/minio/issues/7493
  # -- Set this to true to create ServiceMonitor for Prometheus operator
  serviceMonitor:
    enabled: true
