apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: kube-prometheus-stack
version: 0.1.0
dependencies:
- name: kube-prometheus-stack
  version: 12.2.0
  repository: https://prometheus-community.github.io/helm-charts
