apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "radar-rest-sources-backend.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "radar-rest-sources-backend.name" . }}
    helm.sh/chart: {{ include "radar-rest-sources-backend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "radar-rest-sources-backend.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "radar-rest-sources-backend.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://{{ .Values.postgres.host }}:5432/restsourceauthorizer"
          - name: SPRING_DATASOURCE_USERNAME
            value: {{ .Values.postgres.user }}
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "radar-rest-sources-backend.secretName" . }}
                key: postgresql_password
          - name: REST_SOURCE_AUTHORIZER_SOURCE_CLIENTS_FILE_PATH
            value: app-includes/rest_source_clients_configs.yml
          - name: APP_SLEEP
            value: "10"   # gives time for the database to boot before the application
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - wget --spider http://localhost:8080/users
            initialDelaySeconds: 5
            periodSeconds: 90
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - wget --spider http://localhost:8080/users
            initialDelaySeconds: 5
            periodSeconds: 90
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /app-includes/
      volumes:
        - name: config
          configMap:
            name: {{ include "radar-rest-sources-authorizer.fullname" . }}              
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
