{{- if (include "radar-rest-sources-backend.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "radar-rest-sources-backend.fullname" . }}
  labels:
    app: {{ template "radar-rest-sources-backend.name" . }}
    chart: {{ template "radar-rest-sources-backend.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  postgresql_password: {{ .Values.postgres.password | b64enc | quote }}
{{- end -}}
