graylog:
  rootTimezone: Europe/Amsterdam
  metrics:
    enabled: true
  geoip:
    enabled: true
  ingress:
    enabled: true
    port: 80
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/enable-access-log: "false"
  elasticsearch:
    hosts: http://elasticsearch-master:9200
  input:
    tcp:
      service:
        type: ClusterIP
      ports:
        - name: gelf
          port: 12222
  mongodb:
    uri: mongodb://mongodb-mongodb-replicaset-0.mongodb-mongodb-replicaset:27017/graylog?replicaSet=rs0
tags:
  install-mongodb: false
  install-elasticsearch: false
