prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: "false"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      certmanager.k8s.io/acme-challenge-type: http01
      certmanager.k8s.io/issuer: letsencrypt-prod
    hosts:
      - localhost
    tls:
    - secretName: radar-base-tls
      hosts:
      - localhost

alertmanager:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      certmanager.k8s.io/acme-challenge-type: http01
      certmanager.k8s.io/issuer: letsencrypt-prod
    hosts:
      - localhost
    tls:
    - secretName: radar-base-tls
      hosts:
      - localhost

grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      certmanager.k8s.io/acme-challenge-type: http01
      certmanager.k8s.io/issuer: letsencrypt-prod
    hosts:
      - localhost
    tls:
    - secretName: radar-base-tls
      hosts:
      - localhost
