
replicaCount: 1

service:
  type: ExternalName
  externalName: schema-registry-domain

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/configuration-snippet: |
      limit_except GET {
        deny all;
      }
  path: "/schema/?(.*)"
  hosts:
    - localhost
  tls:
    secretName: radar-base-tls



cc:
  schemaRegistryApiKey: srApiKey
  schemaRegistryApiSecret: srApiSecret