replicaCount: 1

service:
  type: ExternalName
  externalName: schema-registry-domain

ingress:
  enabled: true
  path: "/schema/?(.*)"
  hosts:
    - localhost
  tls:
    secretName: radar-base-tls

cc:
  # -- Confluent cloud schema registry API key
  schemaRegistryApiKey: srApiKey
  # -- Confluent cloud schema registry API secret
  schemaRegistryApiSecret: srApiSecret
