# -- Number of cc-schema-registry-proxy replicas to deploy
replicaCount: 1

service:
  # -- Kubernetes Service type,
  type: ExternalName
  # -- Domain name used for pointing to actual schema registry instance
  externalName: schema-registry-domain

ingress:
  # -- Enable ingress controller resource
  enabled: true
  # -- Path within the url structure
  path: "/schema/?(.*)"
  # -- Hosts to listen requests from
  hosts:
    - localhost
  tls:
    # -- Name of the secret that contains TLS certificates
    secretName: radar-base-tls

cc:
  # -- Confluent cloud schema registry API key
  schemaRegistryApiKey: srApiKey
  # -- Confluent cloud schema registry API secret
  schemaRegistryApiSecret: srApiSecret
