podManagementPolicy: OrderedReady

customEnv:
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
  KAFKA_LOG_RETENTION_HOURS: "730"
  KAFKA_MESSAGE_MAX_BYTES: "4000048"
  KAFKA_LOG4J_LOGGERS: kafka.producer.async.DefaultEventHandler=INFO,kafka.controller=INFO,state.change.logger=INFO
  KAFKA_COMPRESSION_TYPE: lz4
  KAFKA_INTER_BROKER_PROTOCOL_VERSION: "1.1"
  KAFKA_LOG_MESSAGE_FORMAT_VERSION: "1.1"
  KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
  KAFKA_OFFSETS_RETENTION_MINUTES: "10080"
  KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: "16000"


cp-zookeeper:
  enabled: false
  url: "cp-zookeeper-headless:2181"
