helmDefaults:
  atomic: true
  force: true

releases:
  - name: cert
    namespace: cert-manager
    wait: true
    chart: ../charts/cert
    set:
      - name: server_name
        value: {{ requiredEnv "SERVER_NAME" }}
      - name: maintainer_email
        value: {{ requiredEnv "MAINTAINER_EMAIL" }}

  - name: prometheus-operator
    chart: ../charts/prometheus-operator
    atomic: true
    wait: true
    timeout: 600
    namespace: monitoring
    values:
      - "../charts/prometheus-operator/origin-values.yaml"
      - "../charts/prometheus-operator/values.yaml"
    set:
      - name: prometheus.ingress.hosts
        values: ["prometheus.{{ requiredEnv "SERVER_NAME" }}"]
      - name: prometheus.ingress.tls[0].hosts
        values: ["prometheus.{{ requiredEnv "SERVER_NAME" }}"]

      - name: alertmanager.ingress.hosts
        values: ["alertmanager.{{ requiredEnv "SERVER_NAME" }}"]
      - name: alertmanager.ingress.tls[0].hosts
        values: ["alertmanager.{{ requiredEnv "SERVER_NAME" }}"]

      - name: grafana.ingress.hosts
        values: ["grafana.{{ requiredEnv "SERVER_NAME" }}"]
      - name: grafana.ingress.tls[0].hosts
        values: ["grafana.{{ requiredEnv "SERVER_NAME" }}"]

      - name: nginx_auth
        value: "{{ requiredEnv "MONITORING_NGINX_AUTH" }}"

      - name: receivers
        value: |-
          slack_config:
            api_url: "{{ requiredEnv "MONITORING_SLACK_WEBHOOK_URL" }}"
            channel: "{{ requiredEnv "MONITORING_SLACK_CHANNEL" }}"

  - name: nginx-ingress
    chart: stable/nginx-ingress
    version: 1.6.16
    wait: false
    values:
      - "../charts/nginx-ingress/values.yaml"
    set:
      - name: controller.replicaCount
        value: {{ requiredEnv "NGINX_INGRESS_REPLICA_COUNT" }}

  - name: kafka-manager
    chart: ../charts/kafka-manager
    wait: false
    set:
      - name: image.tag
        value: "{{ requiredEnv "KAFKA_MANAGER_IMAGE_TAG" }}"
      - name: ingress.hosts
        values: ["{{ requiredEnv "SERVER_NAME" }}"]
      - name: ingress.tls[0].hosts
        values: ["{{ requiredEnv "SERVER_NAME" }}"]
      - name: basicAuth.enabled
        value: true
      - name: basicAuth.username
        value: "{{ requiredEnv "KAFKA_MANAGER_USERNAME" }}"
      - name: basicAuth.password
        value: "{{ requiredEnv "KAFKA_MANAGER_PASSWORD" }}"
