environments:
  default:
    values:
    - ../base.yaml
    - ../production.yaml

helmDefaults:
  atomic: false
  timeout: 600
  kubeContext: {{ .Values.kubeContext }}

releases:


  - name: management-portal
    chart: ../charts/management-portal
    installed: {{ .Values.management_portal._install }}
    values:
      - {{ .Values.management_portal | toYaml | indent 8 | trim }}
    set:
      - name: ingress.hosts
        values: [{{ .Values.server_name }}]
      - name: server_name
        value: {{ .Values.server_name }}
      - name: postgres.password
        value: {{ .Values.postgres_password }}

