repositories:
- name: rook-release
  url: https://charts.rook.io/release

environments:
  default:
    values:
    - ../base.yaml
    - ../production.yaml

helmDefaults:
  atomic: true
  force: true
  timeout: 600

releases:
  - name: hdfs-namenode
    chart: ../charts/hdfs
    installed: {{ .Values.hdfs_namenode._install }}
    values:
      - "../charts/hdfs/values-namenode.yaml"
      - {{ .Values.hdfs_namenode | toYaml | indent 8 | trim }}
    set:
      - name: volumes[0].size
        value: {{ .Values.hdfs_namenode.namenode_1_disk_size }}
      - name: volumes[1].size
        value: {{ .Values.hdfs_namenode.namenode_2_disk_size }}

  - name: hdfs-datanode
    chart: ../charts/hdfs
    installed: {{ .Values.hdfs_datanode._install }}
    values:
      - "../charts/hdfs/values-datanode.yaml"
      - {{ .Values.hdfs_datanode | toYaml | indent 8 | trim }}
    set:
      - name: volumes[0].size
        value: {{ .Values.hdfs_datanode.disk_size }}

  - name: radar-connect-hdfs-sink
    chart: ../charts/radar-connect-hdfs-sink
    installed: {{ .Values.radar_connect_hdfs_sink._install }}
    values:
      - {{ .Values.radar_connect_hdfs_sink | toYaml | indent 8 | trim }}
    set:
      - name: kafka_num_brokers
        value: {{ .Values.kafka_num_brokers }}


  - name: radar-output
    chart: ../charts/radar-output
    wait: true
    installed: {{ .Values.radar_output._install }}
    values:
      - {{ .Values.radar_output | toYaml | indent 8 | trim }}
