environments:
  default:
    values:
    - ../base.yaml
    - ../production.yaml

helmDefaults:
  atomic: true
  timeout: 600
  kubeContext: {{ .Values.kubeContext }}
  
releases:

  - name: radar-gateway
    chart: ../charts/radar-gateway
    installed: {{ .Values.radar_gateway._install }}
    values:
      - {{ .Values.radar_gateway | toYaml | indent 8 | trim }}
      - {{ .Values.confluentCloud| toYaml | indent 8 | trim }}
    set:
      - name: ingress.hosts
        values: [{{ .Values.server_name }}]
      - name: cc.enabled
        value: {{ .Values.confluentCloud.enabled }}
      - name: serviceMonitor.enabled
        value: {{ .Values.prometheus_operator._install }}
      {{- if .Values.confluentCloud.enabled }}
      - name: schemaRegistry
        value: {{ .Values.confluentCloud.cc.schemaRegistryUrl }}
      - name: bootstrapServers
        value: {{ .Values.confluentCloud.cc.bootstrapServerurl }}
      {{ end }}
