environments:
  default:
    values:
    - ../base.yaml
    - ../production.yaml

helmDefaults:
  atomic: true
  timeout: 600
  kubeContext: {{ .Values.kubeContext }}
  
releases:
  - name: cp-kafka-rest
    chart: ../cp-helm-charts/charts/cp-kafka-rest
    wait: false
    installed: {{ .Values.cp_kafka_rest._install }}
    values:
      - "../charts/cp-kafka-rest/values.yaml"
      - {{ .Values.cp_kafka_rest | toYaml | indent 8 | trim }}

  - name: radar-gateway
    chart: ../charts/radar-gateway
    installed: {{ .Values.radar_gateway._install }}
    values:
      - {{ .Values.radar_gateway | toYaml | indent 8 | trim }}
      - {{ .Values.confluentCloud| toYaml | indent 8 | trim }}
    set:
      - name: ingress.hosts
        values: [{{ .Values.server_name }}]
      - name: cc.enabled
        value: {{ .Values.confluentCloud.enabled }}
      {{- if .Values.confluentCloud.enabled }}
      - name: schemaRegistry
        value: {{ .Values.confluentCloud.cc.schemaRegistryUrl }}
      - name: bootstrapServers
        value: {{ .Values.confluentCloud.cc.bootstrapServerurl }}
      {{ end }}
