bases:
- ../environments.yaml

---

{{ readFile "../etc/helmfile-templates.yaml" }}

releases:
  - name: radar-backend-monitor
    chart: radar/radar-backend
    version: {{ .Values.radar_backend_monitor._chart_version }}
    installed: {{ .Values.radar_backend_monitor._install }}
    timeout: {{ dig "_timeout" .Values.timeout .Values.radar_backend_monitor }}
    <<: *logFailedRelease
    values:
      - "../etc/radar-backend-monitor/values.yaml"
      - {{ .Values.radar_backend_monitor | toYaml | indent 8 | trim }}
    set:
      - name: kafka_num_brokers
        value: {{ .Values.kafka_num_brokers }}

  - name: radar-backend-stream
    chart: radar/radar-backend
    version: {{ .Values.radar_backend_monitor._chart_version }}
    installed: {{ .Values.radar_backend_stream._install }}
    timeout: {{ dig "_timeout" .Values.timeout .Values.radar_backend_stream }}
    <<: *logFailedRelease    
    values:
      - "../etc/radar-backend-stream/values.yaml"
      - {{ .Values.radar_backend_stream | toYaml | indent 8 | trim }}
    set:
      - name: kafka_num_brokers
        value: {{ .Values.kafka_num_brokers }}
