helmDefaults:
  atomic: true
  wait: false

releases:
  - name: radar-backend-monitor
    chart: ../charts/radar-backend
    installed: {{ requiredEnv "RADAR_INSTALL_KAFKA_ANALYSIS" }}
    values:
    - "../charts/radar-backend/values-monitor.yaml"
    - image:
        tag: "{{ requiredEnv "RADAR_BACKEND_IMAGE_TAG" }}"
      replicaCount: "{{ requiredEnv "RADAR_BACKEND_MONITOR_REPLICA_COUNT" }}"
      kafka_num_brokers: "{{ requiredEnv "KAFKA_NUM_BROKERS" }}"
  - name: radar-backend-stream
    chart: ../charts/radar-backend
    installed: {{ requiredEnv "RADAR_INSTALL_KAFKA_ANALYSIS" }}
    values:
    - "../charts/radar-backend/values-stream.yaml"
    - image:
        tag: "{{ requiredEnv "RADAR_BACKEND_IMAGE_TAG" }}"
      replicaCount: "{{ requiredEnv "RADAR_BACKEND_STREAM_REPLICA_COUNT" }}"
      kafka_num_brokers: "{{ requiredEnv "KAFKA_NUM_BROKERS" }}"
  - name: smtp
    chart: ../charts/smtp
    installed: {{ requiredEnv "RADAR_INSTALL_KAFKA_ANALYSIS" }}
    values:
    - replicaCount: "{{ requiredEnv "SMTP_REPLICA_COUNT" }}"
      smarthost:
        address: "{{ requiredEnv "SMTP_ADDRESS" }}"
        user: "{{ requiredEnv "SMTP_USER" }}"
        password: "{{ requiredEnv "SMTP_PASSWORD" }}"
