bases:
- ../environments.yaml

---

repositories:
- name: minio
  url: https://helm.min.io/
- name: bitnami
  url: https://charts.bitnami.com/bitnami

helmDefaults:
  atomic: false
  timeout: 240
  kubeContext: {{ .Values.kubeContext }}

releases:
  - name: redis
    chart: bitnami/redis
    version: 10.6.15
    installed: {{ .Values.redis._install }}
    values:
      - "../etc/redis/values.yaml"
      - {{ .Values.redis | toYaml | indent 8 | trim }}

  - name: minio
    chart: minio/minio
    version: 8.0.10
    installed: {{ .Values.minio._install }}
    values:
      - "../etc/minio/values.yaml"
      - {{ .Values.minio | toYaml | indent 8 | trim }}
    set:
      - name: ingress.hosts
        values: ["s3.{{ .Values.server_name }}"]
      - name: ingress.tls[0].secretName
        value: radar-base-tls-s3
      - name: ingress.tls[0].hosts
        values: ["s3.{{ .Values.server_name }}"]

  - name: radar-s3-connector
    chart: ../charts/radar-s3-connector
    installed: {{ .Values.radar_s3_connector._install }}
    values:
      - {{ .Values.radar_s3_connector | toYaml | indent 8 | trim }}
      - {{ .Values.confluent_cloud | toYaml | indent 8 | trim }}
    set:
      - name: cc.enabled
        value: {{ .Values.confluent_cloud.enabled }}

  - name: s3-proxy
    chart: ../charts/s3-proxy
    installed: {{ .Values.s3_proxy._install }}
    values:
      - {{ .Values.s3_proxy | toYaml | indent 8 | trim }}

  - name: radar-output
    chart: ../charts/radar-output
    wait: true
    installed: {{ .Values.radar_output._install }}
    values:
      - {{ .Values.radar_output | toYaml | indent 8 | trim }}
