bases:
- ../environments.yaml

---

{{ readFile "../etc/helmfile-templates.yaml" }}

releases:
  - name: cc-schema-registry-proxy
    chart: radar/cc-schema-registry-proxy
    version: {{ .Values.ccSchemaRegistryProxy._chart_version }}
    installed: {{ .Values.ccSchemaRegistryProxy._install }}
    <<: *logFailedRelease    
    values:
      - {{ .Values.ccSchemaRegistryProxy | toYaml | indent 8 | trim }}
      - {{ .Values.confluent_cloud| toYaml | indent 8 | trim }}
    set:
      - name: service.externalName
        value: {{ .Values.ccSchemaRegistryProxy.externalName }}
      - name: ingress.hosts
        values: [{{ .Values.server_name }}]
