bases:
- ../environments.yaml

---

{{ readFile "../etc/helmfile-templates.yaml" }}

releases:
  - name: velero
    namespace: velero
    chart: radar/velero-s3-deployment
    version: {{ .Values.velero._chart_version }}
    installed: {{ .Values.velero._install }}
    timeout: {{ dig "_timeout" .Values.timeout .Values.velero }}
    <<: *logFailedRelease
    values:
      - {{ .Values.velero | toYaml | indent 8 | trim }}
    set:
      - name: local.accessKey
        value: {{ dig "local" "accessKey" .Values.s3_access_key .Values.velero }}
      - name: local.secretKey
        value: {{ dig "local" "secretKey" .Values.s3_secret_key .Values.velero }}
