bases:
- ../environments.yaml

---

helmDefaults:
  atomic: true
  timeout: 120
  kubeContext: {{ .Values.kubeContext }}

repositories:
  - name: radar
    url: https://radar-base.github.io/radar-helm-charts

releases:
  - name: velero
    chart: radar/velero
    namespace: velero
    version: {{ .Values.velero._chart_version }}
    installed: {{ .Values.velero._install }}
    values:
      - {{ .Values.velero | toYaml | indent 8 | trim }}
