bases:
- ../environments.yaml

---

helmDefaults:
  atomic: true
  timeout: 120
  kubeContext: {{ .Values.kubeContext }}

repositories:
  - name: radar
    url: https://radar-base.github.io/radar-helm-charts

releases:
  - name: velero
    chart: radar/velero-s3-deployment
    namespace: velero
    version: {{ .Values.velero._chart_version }}
    installed: {{ .Values.velero._install }}
    values:
      - {{ .Values.velero | toYaml | indent 8 | trim }}
    set:
      {{- if not (hasKey .Values.velero "local.accessKey") }}
      - name: local.accessKey
        value: {{ .Values.s3_access_key }}
      {{- end }}
      {{- if not (hasKey .Values.velero "local.secretKey") }}
      - name: local.secretKey
        value: {{ .Values.s3_secret_key }}
      {{- end }}
