# Default values for rook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image_tools:
  repository: rook/ceph
  tag: v1.2.3
  pullPolicy: IfNotPresent

image_ceph:
  repository: ceph/ceph
  tag: v14.2.6

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ceph_cluster:
  mon:
    count: 3
    claim:
      storage:
        class: cinder
        size: 10Gi
  storage:
    name: set1
    count: 3
    claim:
      name: data
      storage:
        size: 20Gi
        class: cinder
