apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "radar-upload-source-connector.fullname" . }}
  labels:
    app: {{ template "radar-upload-source-connector.name" . }}
    chart: {{ template "radar-upload-source-connector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  source-upload.properties: |
    name=radar-upload-source
    connector.class=org.radarbase.connect.upload.UploadSourceConnector
    tasks.max=4
    upload.source.client.id={{ .Values.client_id }}
    upload.source.client.secret={{ .Values.client_secret }}
    upload.source.client.tokenUrl=http://{{ .Values.managementportal_host }}:8080/managementportal/oauth/token
    upload.source.backend.baseUrl=http://{{ .Values.radar_upload_connect_backend }}:8085/upload/api/
    upload.source.poll.interval.ms={{ .Values.poll_interval }}
    upload.source.record.converter.classes={{ .Values.record_converter_classes }}
    upload.source.file.uploader.type={{ .Values.uploaderType }}
    upload.source.file.uploader.target.endpoint={{ .Values.s3Endpoint }}
    upload.source.file.uploader.target.root.directory={{ .Values.targetBucketName }}
    upload.source.file.uploader.username={{ .Values.bucketAccessKey }}
    upload.source.file.uploader.password={{ .Values.bucketSecretKey }}