name: CI
on:
  push:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Cleanup
      continue-on-error: true
      run: |
        ls -la ./
        rm -rf ./* || true
        rm -rf ./.??* || true
        ls -la ./
        k3s-uninstall.sh

    - uses: actions/checkout@v1.0.0

    - name: Install dependencies
      env:
        KUBECTL_VERSION: "v1.25.4"
        HELM_VERSION: "v3.10.2"
        HELM_DIFF_VERSION: "3.4.2"
        HELMFILE_VERSION: "v0.148.1"
        YQ_VERSION: "v4.30.1"
      run: |
        ./.github/ci_config/bin/install-dependencies

    - name: Prepare the environment
      run: |
        DNAME='CN=CI,O=TheHyve,L=Utrecht,C=NL' ./bin/init
        yq -i -f process '.environments.default.values += ["../.github/ci_config/install-all.yaml", "../.github/ci_config/secrets.yaml.gotmpl"]' environments.yaml

    - name: Run helmfile template
      env:
        FIREBASE_ADMINSDK_JSON: ${{ secrets.FIREBASE_ADMINSDK_JSON }}
      run: |
        helmfile template

    - name: Start a local k8s cluster
      uses: jupyterhub/action-k3s-helm@v3
      with:
        # See available:
        # - k3s release channels at https://github.com/k3s-io/k3s/blob/HEAD/channel.yaml
        # - k3s versions at https://github.com/k3s-io/k3s/tags
        # - helm versions at https://github.com/helm/helm/tags
        k3s-channel: v1.25.3+k3s1
        traefik-enabled: false

    - name: Install RADAR-Kubernetes
      env:
        FIREBASE_ADMINSDK_JSON: ${{ secrets.FIREBASE_ADMINSDK_JSON }}
      run: |
        echo "kubeconfig: $KUBECONFIG"
        kubectl get pods --all-namespaces

        helmfile sync --concurrency 1

    # Enable tmate debugging of manually-triggered workflows if the input option was provided
    - name: Manually triggered tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      with:
        limit-access-to-actor: true

    - name: Setup tmate session if jobs have failed
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 15
      with:
        limit-access-to-actor: true

    - name: Report cluster state
      if: always()
      run: |
        kubectl get pods --all-namespaces
