name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup helmfile
      uses: mamezou-tech/setup-helmfile@v1.2.0

    - name: Set up helmfile config
      run: cp .github/environments.yaml environments.yaml

    - name: Run helmfile template
      run: |
        helmfile template

    # - name: Start a local k8s cluster
    #   uses: jupyterhub/action-k3s-helm@v3
    #   with:
    #     # See available:
    #     # - k3s release channels at https://github.com/k3s-io/k3s/blob/HEAD/channel.yaml
    #     # - k3s versions at https://github.com/k3s-io/k3s/tags
    #     # - helm versions at https://github.com/helm/helm/tags
    #     k3s-channel: latest
    #
    # - name: Verify function of k8s, kubectl, and helm
    #   run: |
    #     echo "kubeconfig: $KUBECONFIG"
    #     kubectl version
    #     kubectl get pods --all-namespaces
    #
    #     helmfile sync --concurrency 1
  check-gitignore:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Check gitignore
      run: |
        echo "Checking whether any files that should be ignored are uploaded"
        echo
        if find . -not -path './.git/*' -type f | git check-ignore --stdin --no-index; then
          echo
          echo "Remove the above files from this branch"
          exit 1
        else
          echo "No ignored files have been added"
        fi
