name: Check dependency updates

on:
  pull_request: {}
  workflow_dispatch: {}
  schedule:
    - cron: '30 5 * * 1'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup-helmfile
        uses: mamezou-tech/setup-helmfile@v0.9.0
        with:
          install-helm-plugins: no
          install-kubectl: no
      - name: setup helmfile config
        run: |
          cp .github/environments.yaml environments.yaml
      
      - name: Check updates
        run: bin/dependency-updates
