name: Update versions.md

on:
  push:
    branches:
      - version_scan

jobs:
  update_versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: setup-helmfile
        uses: mamezou-tech/setup-helmfile@v1.2.0
        with:
          install-helm-plugins: no
          install-kubectl: no

      - name: Update versions.md
        run: bin/version_scan

      - name: Commit and push if versions.md changed
        run: |
          git diff
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git commit -am "Update versions.md" || exit 0
          git push