postgres_password: password

# --------------------------------------------------------- 00-init.yaml ---------------------------------------------------------
mongodb:
  auth:
    replicaSetKey: secret
    rootPassword: secret

kube_prometheus_stack:
    alertmanager:
      config:
        receivers:
          - name: default
            slack_configs:
              - api_url: https://hooks.slack.com/services/XXXXXX/XXXXXX/XXXXXXXXXX
                channel: "#radar-ops"
    grafana:
      adminPassword: "password"
    # encode with "MYUSERNAME:"$(openssl passwd -apr1 MYPASSWORD)
    nginx_auth: "test:$apr1$s5C61r9E$kFpp71zFuP7WYiHlA.2Tb1"  # test:test


kafka_manager:
  basicAuth:
    enabled: true
    username: kafkamanager-user
    password: password

velero:
  local:
    accessKey: accessKey
    secretKey: secretKey
  backup:
    accessKey: accessKey
    secretKey: secretKey
  velero:
    credentials:
      secretContents:
        cloud: |
          [default]
          aws_access_key_id=accessKey
          aws_secret_access_key=secretKey

confluent_cloud:
  cc:
    apiKey: ccApikey
    apiSecret: ccApiSecret
    schemaRegistryApiKey: srApiKey
    schemaRegistryApiSecret: srApiSecret

management_portal:
  postgres:
    # If the postgresql storage chart is used, the postgres password should match `postgres_password`.
    password: password
    ssl:
      keystorepassword: keystorepassword
  managementportal:
    common_admin_password: password
    frontend_client_secret: password
  oauth_clients:
    radar_upload_backend:
      client_secret: secret
    radar_upload_connect:
      client_secret: secret
    radar_rest_sources_auth_backend:
      client_secret: secret
    radar_redcap_integrator:
      client_secret: secret
    radar_fitbit_connector:
      client_secret: secret
    radar_appconfig:
      client_secret: secret
  smtp:
    username: username
    password: secret

# If the postgresql storage chart is used, the postgres password should match `postgres_password`.
app_config:
  jdbc:
    password: password

# --------------------------------------------------------- 20-fitbit.yaml ---------------------------------------------------------
fitbit_api_client: fitbit_api_client_id
fitbit_api_secret: fitbit_api_client_secret

# If the postgresql storage chart is used, the postgres password should match `postgres_password`.
radar_rest_sources_backend:
  postgres:
    user: postgres
    password: password
    ssl:
      keystorepassword: keystorepassword

# --------------------------------------------------------- 20-s3-connector.yaml ---------------------------------------------------------

# The following access keys and secret keys should match. If S3 is used as a storage medium instead of minio, then fill in those.

minio:
  accessKey: AKIAIOSFODNN7EXAMPLE
  secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

radar_s3_connector:
  bucketAccessKey: AKIAIOSFODNN7EXAMPLE
  bucketSecretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

s3_proxy:
  s3:
    identity: AKIAIOSFODNN7EXAMPLE
    credential: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

radar_output:
  source:
    s3:
      accessToken: AKIAIOSFODNN7EXAMPLE
      secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  target:
    s3:
      accessToken: AKIAIOSFODNN7EXAMPLE
      secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

# --------------------------------------------------------- 20-grafana.yaml ---------------------------------------------------------

timescaledb_password: password
timescaledb_username: postgres

grafana_password: password
grafana_metrics_username: username
grafana_metrics_password: password
